### PR TITLE
Change output format type to str

### PR DESCRIPTION
**Pull request by Alliad**
@dzmitry-lahoda , check, please, schema:

[
  {
    "out_asset_amount": "string",
    "out_asset_id": "string",
    "in_asset_amount": "string",
    "in_asset_id": "string",
    "next": [
      {
        "out_asset_amount": "string",
        "out_asset_id": "string",
        "in_asset_amount": "string",
        "in_asset_id": "string",
        "pool_id": "string",
        "next": [
          {},
          {
            "out_asset_amount": "string",
            "out_asset_id": "string",
            "in_asset_amount": "string",
            "in_asset_id": "string",
            "next": [
              "string",
              "string"
            ]
          }
        ]
      },
      {
        "out_asset_amount": "string",
        "out_asset_id": "string",
        "in_asset_amount": "string",
        "in_asset_id": "string",
        "pool_id": "string",
        "next": [
          "string",
          "string"
        ]
      }
    ]
  }
]

### CODE REVIEW

**Comment by dzmitry-lahoda** [comment]
simple fields seems correct in schema. all correct. 

so

```json
"next": [
"string",
"string"
]
```
fields wrong.

**Comment by dzmitry-lahoda** [comment]
@Alliad may you test change works? like call API endpoint?

**Comment by dzmitry-lahoda** [comment]
so what should work:
1. ids, amoints in json schema are strings
2. next - is stuctured object
3. in python code generic type is int(integer) and/or float, but NOT str(string).
4. calling endpoint to find route should work as I shown before (recall video I shared)
5. Input also to be string for id and amount, but parsed into int
6. tests and typechecks passed before should work after changes (construction of output/input instances to pass type checker and be creatable)


thing check how it looks/works before your changes and after

**Comment by dzmitry-lahoda** [comment]
@Alliad how it is going? we may try pair programming

**Comment by dzmitry-lahoda** [comment]
or may you comment what is working/what not. what this PR fixes from things dicussed. 1. enpoint works or not with and without pr. 2. serde is str or not in this pr 3. schema str or not for next field

**Comment by Alliad** [comment]
> or may you comment what is working/what not. what this PR fixes from things dicussed. 1. enpoint works or not with and without pr. 2. serde is str or not in this pr 3. schema str or not for next field

1. For me, endpoint dont work from that PR and from last changes in main and from commit c01fde916e1736b81777ab126ed50dd14e235bf9
2. This PR should fix str in json-schema and 3.) in next field, but I cant test this

I am currently investigating why the route search is not working.

**Pull request closed without merging**
