### PR TITLE
formatting by black and ruff 

### PR DESCRIPTION
**Pull request by olegkiselevgit**

### CODE REVIEW

**Comment by olegkiselevgit** [comment]
It write that numpy is not founded , but in pyproject.toml it exists:
numpy = "1.23.4"

**Comment by dzmitry-lahoda** [comment]
@olegkiselevgit 

from CI:
````
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.
```

please run `poetry lock --no-update` and push lock file

**Comment by dzmitry-lahoda** [comment]
@olegkiselevgit numpy found on others PR, so likely it is this PR change

**Comment by dzmitry-lahoda** [comment]
fixed in my pr. just used ruff

**Pull request closed without merging**
