### PR TITLE
Add COWs + MM paper

### PR DESCRIPTION
**Pull request by JafarAz**

### CODE REVIEW

**Review by blasrodri — APPROVED** [review]

**Comment by dzmitry-lahoda** [comment]
@JafarAz do we want to publish into this repo? I think easy to create whatever repo arXive like to send pds

**Comment by JafarAz** [comment]
I guess we can always move later but @0xBrainjar2 asked for it to be posted here for now

**Comment by dzmitry-lahoda** [comment]
ok:) fixing PR from fork:)  that is never works as never tested

**Comment by JafarAz** [comment]
@dzmitry-lahoda I do not have write access so I had to use fork, if you give me write access i will quickly redo PR

**Comment by dzmitry-lahoda** [comment]
@JafarAz I automated write access with env repo like this https://github.com/ComposableFi/env/issues/12

it could take me half hour to have new repo with rights like docs or arxive to publish rendered pdfs. so it can have its own ci (none for now - simle) and never changes its stucture and location so pdfs are frozen to links

**Pull request merged**
